version: "3.8"
services:
  cc-service:
    container_name: obatin-api
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - HOST=
      - PORT=
      - DB_HOST=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DATABASE=
      - DB_DIALECT=
      - ACCESS_TOKEN_AGE=
      - ACCESS_TOKEN_KEY=
      - REFRESH_TOKEN_KEY=
      - ML_API=
